# Generated by Django 4.0.4 on 2022-05-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_device_user_device_id_user_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.BigIntegerField(max_length=12, unique=True),
        ),
    ]
