# Generated by Django 4.0.4 on 2022-06-02 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 16, 43, 59, 425290, tzinfo=utc)),
        ),
    ]
