# Generated by Django 4.0.4 on 2022-06-03 01:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_usersession_jwt_secret_alter_usersession_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='jwt_secret',
        ),
        migrations.AddField(
            model_name='usersession',
            name='access_token',
            field=models.TextField(db_index=True, default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 1, 17, 19, 986003, tzinfo=utc)),
        ),
    ]
