# Generated by Django 4.0.4 on 2022-06-04 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_usersession_jwt_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 6, 26, 9, 544856, tzinfo=utc)),
        ),
    ]
