# Generated by Django 4.0.4 on 2022-06-19 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_usersession_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 10, 7, 54, 845025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 10, 7, 54, 844761, tzinfo=utc)),
        ),
    ]
