version: "3.8"
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #entrypoint: ./entrypoint.sh
    env_file:
      - .env
    volumes:
      - .:/gtouch
    ports:
      - "80:8000"
  # celery:
  #     build: .
  #     command: celery -A config worker -l INFO
  #     env_file:
  #       - .env
  #     volumes:
  #         - .:/usr/src/app      
  #     depends_on:
  #         - web
  # celery_beat:
  #     build: .
  #     command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #     env_file:
  #       - .env
  #     volumes:
  #         - .:/usr/src/app
  #     depends_on:
  #         - web
  #         - celery
