"""
Django settings for gtouch project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from .settings import *
import os
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "postgres",
        "USER": "postgres",
        "PASSWORD": "4k;(*o*Jw;)S",
        "HOST": "gtouchdb.ctd1uaup1ns8.ap-south-1.rds.amazonaws.com",
        "PORT": 5432,
    }
}
