# Generated by Django 4.0.4 on 2022-05-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0003_alter_videomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videomodel',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Video'},
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='category',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='video.category'),
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watch_duration_time', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='history_user', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_history_video', to='video.videomodel')),
            ],
            options={
                'verbose_name_plural': 'User History',
            },
        ),
        migrations.CreateModel(
            name='FavoritVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fav_user', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fav_video', to='video.videomodel')),
            ],
            options={
                'verbose_name_plural': 'Favorit Video',
            },
        ),
    ]
