# Generated by Django 4.0.4 on 2022-05-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_category_options_category_parent_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='cast_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
