# Generated by Django 4.0.4 on 2022-05-28 07:27

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_videomodel_cast_details_videomodel_show_on_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 28, 7, 27, 6, 163484, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'NOT_ACTIVE'), (1, 'ACTIVE')], default=1)),
                ('is_delete', models.IntegerField(choices=[(0, 'NOT_DELETE'), (1, 'DELETED')], default=0)),
            ],
            options={
                'verbose_name_plural': 'sections',
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 7, 27, 6, 163484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='favoritvideo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 7, 27, 6, 163484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 7, 27, 6, 163484, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 28, 7, 27, 6, 163484, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, upload_to='video_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['WEBM', 'MPG', 'MP2', 'MPEG', 'MPE', 'MPV', 'OGG', 'MP4', 'M4P', 'M4V', 'AVI', 'WMV', 'MOV', 'QT', 'FLV', 'SWF'])])),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
                ('is_delete', models.IntegerField(choices=[(0, 'NOT_DELETE'), (1, 'DELETED')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'NOT_ACTIVE'), (1, 'ACTIVE')], default=1)),
                ('show_on_home', models.BooleanField(default=False)),
                ('cast_details', models.TextField(blank=True, null=True)),
                ('video_type', models.IntegerField(choices=[(1, 'NORAMAL'), (2, 'SERIES')], default=1)),
                ('url', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='video.category')),
                ('section', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sesctions', to='video.sections')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Video',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='favoritvideo',
            name='video',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fav_video', to='video.video'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='video',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_history_video', to='video.video'),
        ),
        migrations.DeleteModel(
            name='VideoModel',
        ),
    ]
