# Generated by Django 4.0.4 on 2022-05-28 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_live_news_homepage_remove_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='live',
            options={'verbose_name_plural': 'live'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 8, 31, 40, 965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='favoritvideo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 8, 31, 40, 965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='live',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 8, 31, 40, 965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 8, 31, 40, 965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sections',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 8, 31, 40, 965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 8, 31, 40, 965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 8, 31, 40, 965, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='video',
            name='section',
        ),
        migrations.AddField(
            model_name='video',
            name='section',
            field=models.ManyToManyField(related_name='sesctions', to='video.sections'),
        ),
    ]
