# Generated by Django 4.0.4 on 2022-06-17 07:23

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0023_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='h_thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/video_thumbnail/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'jpe', 'jpg', 'jpeg', 'tif', 'gif', 'ppm', 'xbm', 'tiff', 'rgb', 'pgm', 'png', 'pnm'])], verbose_name='Horizontal Thumbnail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 7, 23, 4, 323132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='favoritvideo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 7, 23, 4, 323132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='live',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 7, 23, 4, 323132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 7, 23, 4, 323132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sections',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 7, 23, 4, 323132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 7, 23, 4, 323132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 7, 23, 4, 323132, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='static/video_thumbnail/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'jpe', 'jpg', 'jpeg', 'tif', 'gif', 'ppm', 'xbm', 'tiff', 'rgb', 'pgm', 'png', 'pnm'])], verbose_name='Vertical Thumbnail'),
        ),
    ]
